// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShelterHack.Models;

namespace ShelterHack.Migrations
{
    [DbContext(typeof(ShelterContext))]
    partial class ShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ShelterHack.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("ArrivedInShelter")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CatcherEmployeeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ContainerShelterId")
                        .HasColumnType("integer");

                    b.Property<int?>("ContractId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CatcherEmployeeId");

                    b.HasIndex("ContainerShelterId");

                    b.HasIndex("ContractId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("ShelterHack.Models.AuthData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuthData");
                });

            modelBuilder.Entity("ShelterHack.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<int?>("PerformerShelterId")
                        .HasColumnType("integer");

                    b.Property<string>("Point")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PerformerShelterId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("ShelterHack.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("ContractId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeclarantShelterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("DeclarantShelterId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("ShelterHack.Models.Shelter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Shelters");
                });

            modelBuilder.Entity("ShelterHack.Models.ShelterEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AuthDataId")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<int?>("ShelterId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthDataId");

                    b.HasIndex("ShelterId");

                    b.ToTable("ShelterEmployees");
                });

            modelBuilder.Entity("ShelterHack.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AuthDataId")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthDataId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShelterHack.Models.Animal", b =>
                {
                    b.HasOne("ShelterHack.Models.ShelterEmployee", "CatcherEmployee")
                        .WithMany("CaughtAnimals")
                        .HasForeignKey("CatcherEmployeeId");

                    b.HasOne("ShelterHack.Models.Shelter", "ContainerShelter")
                        .WithMany("ContainingAnimals")
                        .HasForeignKey("ContainerShelterId");

                    b.HasOne("ShelterHack.Models.Contract", null)
                        .WithMany("CaughtAnimals")
                        .HasForeignKey("ContractId");
                });

            modelBuilder.Entity("ShelterHack.Models.Contract", b =>
                {
                    b.HasOne("ShelterHack.Models.Shelter", "PerformerShelter")
                        .WithMany("PreformingContracts")
                        .HasForeignKey("PerformerShelterId");
                });

            modelBuilder.Entity("ShelterHack.Models.Request", b =>
                {
                    b.HasOne("ShelterHack.Models.Contract", "Contract")
                        .WithMany("Requests")
                        .HasForeignKey("ContractId");

                    b.HasOne("ShelterHack.Models.Shelter", "DeclarantShelter")
                        .WithMany()
                        .HasForeignKey("DeclarantShelterId");
                });

            modelBuilder.Entity("ShelterHack.Models.ShelterEmployee", b =>
                {
                    b.HasOne("ShelterHack.Models.AuthData", "AuthData")
                        .WithMany()
                        .HasForeignKey("AuthDataId");

                    b.HasOne("ShelterHack.Models.Shelter", "Shelter")
                        .WithMany("Employees")
                        .HasForeignKey("ShelterId");
                });

            modelBuilder.Entity("ShelterHack.Models.User", b =>
                {
                    b.HasOne("ShelterHack.Models.AuthData", "AuthData")
                        .WithMany()
                        .HasForeignKey("AuthDataId");
                });
#pragma warning restore 612, 618
        }
    }
}
